---
count: 4
default:
  restart: 0
  wait: 0
editor:
  files:
    eg:
      - some-file.eg
name: type-categories
terminals:
  1a:
    command: ./Build && ./Build testcover
    restart: 1
    wait: 0
    # watch is a list of files (or file groups) to watch for changes and
    # re-run the command. This watch waits for changes in files in the
    # lib bin and tests directories and then runs tests
    watch:
      - lib
      - bin
      - all-tests
  2:
    edit:
        - lib
        - bin
